// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BiliLogin() {
  return window['go']['main']['App']['BiliLogin']();
}

export function DownloadVedio(arg1, arg2) {
  return window['go']['main']['App']['DownloadVedio'](arg1, arg2);
}

export function GetAvatar() {
  return window['go']['main']['App']['GetAvatar']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetCookie() {
  return window['go']['main']['App']['GetCookie']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenDir() {
  return window['go']['main']['App']['OpenDir']();
}

export function OpenFileExplorer(arg1) {
  return window['go']['main']['App']['OpenFileExplorer'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
