// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function BiliLogin():Promise<string>;

export function DownloadVedio(arg1:string,arg2:string):Promise<string>;

export function GetAvatar():Promise<string>;

export function GetClipboard():Promise<string>;

export function GetCookie():Promise<void>;

export function GetVideoInfo(arg1:string):Promise<app.VideoInfo>;

export function Minimize():Promise<void>;

export function OpenDir():Promise<string>;

export function OpenFileExplorer(arg1:string):Promise<void>;

export function Quit():Promise<void>;
